In [51]:
import torch
import torch.nn.functional as F

In [134]:
torch.manual_seed(0)
x = torch.ones(5)
y = torch.Tensor([0, 0, 0])
W = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = x@W+b
print(y)
print(z)
loss = F.binary_cross_entropy_with_logits(z, y)
print(loss)
yp = 1/(1+torch.exp(-z))
-(y*torch.log(yp)+(1-y)*torch.log(1-yp)).mean()

tensor([0., 0., 0.])
tensor([ 1.3755, -0.6023, -4.8127], grad_fn=<AddBackward0>)
tensor(0.6819, grad_fn=<BinaryCrossEntropyWithLogitsBackward>)


tensor(0.6819, grad_fn=<NegBackward>)

In [118]:
x = torch.randn(10, 4)
target = torch.randint(4, size=(10,), dtype=torch.long)
print(x)
print(target)

tensor([[ 4.3970e-01,  1.1241e-01,  6.4079e-01,  4.4116e-01],
        [-2.1586e-01, -7.4255e-01,  5.6272e-01,  2.5963e-01],
        [ 5.2286e-01,  2.3022e+00, -1.4689e+00, -1.5867e+00],
        [ 1.2032e+00,  8.4535e-02, -1.2001e+00, -4.7857e-03],
        [-2.3034e-01, -3.9175e-01,  5.4329e-01, -3.9516e-01],
        [ 2.0553e-01, -4.5033e-01, -5.7308e-01, -5.5536e-01],
        [-1.1256e+00, -3.1700e-01, -1.0925e+00, -8.5194e-02],
        [-9.3348e-02,  6.8705e-01, -8.3832e-01,  8.9182e-04],
        [-7.5043e-01,  1.8541e-01,  6.2114e-01,  6.3818e-01],
        [-2.4600e-01,  2.3025e+00, -1.8817e+00, -4.9727e-02]])
tensor([2, 2, 3, 0, 2, 3, 1, 0, 1, 2])


In [119]:
y = torch.zeros(10, 4)
y[range(10), target] = 1
y

tensor([[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [ ]:
# binary cross entropy with logit
# class가 여러개면 -> target을 one hot encoding 해
# 예측한 z도 같은 판떼기에서 나오잖아
# z를 sigmoid 넣어줘 (x)
# y*log(x)+ (1-y)*log(1-x)
# 위에꺼를 -mean을 쳐

In [127]:
y_pred = 1/(1+torch.exp(-x))
loss = -(y*torch.log(y_pred)+(1-y)*torch.log(1-y_pred)).mean()
loss

tensor(0.7800)

In [130]:
F.binary_cross_entropy_with_logits(x, y)

tensor(0.7800)

In [177]:

torch.manual_seed(0)
x = torch.ones(5)
y = torch.Tensor([0, 0, 0])
W = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = x@W+b
loss = F.binary_cross_entropy_with_logits(z, y)
optimizer = torch.optim.SGD([W, b], lr=0.9)
print(W)
print(b)
print(z)
print(loss)

tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193],
        [-0.4033, -0.5966,  0.1820],
        [-0.8567,  1.1006, -1.0712]], requires_grad=True)
tensor([ 0.1227, -0.5663,  0.3731], requires_grad=True)
tensor([ 1.3755, -0.6023, -4.8127], grad_fn=<AddBackward0>)
tensor(0.6819, grad_fn=<BinaryCrossEntropyWithLogitsBackward>)


In [178]:
optimizer.zero_grad()
loss.backward()
W-W.grad*0.9, b-b.grad*0.9

(tensor([[ 1.3015, -0.3996, -2.1812],
         [ 0.3290, -1.1907, -1.4010],
         [ 0.1639,  0.7319, -0.7217],
         [-0.6428, -0.7028,  0.1796],
         [-1.0962,  0.9945, -1.0736]], grad_fn=<SubBackward0>),
 tensor([-0.1168, -0.6725,  0.3707], grad_fn=<SubBackward0>))

In [180]:
optimizer.step()

In [182]:
print(W)
print(b)

tensor([[ 1.3015, -0.3996, -2.1812],
        [ 0.3290, -1.1907, -1.4010],
        [ 0.1639,  0.7319, -0.7217],
        [-0.6428, -0.7028,  0.1796],
        [-1.0962,  0.9945, -1.0736]], requires_grad=True)
tensor([-0.1168, -0.6725,  0.3707], requires_grad=True)


In [185]:
optimizer.zero_grad()
W.grad, b.grad

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([0., 0., 0.]))