In [50]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [66]:
# data = [[1, 2], [3, 4]]
data = np.ones(1000)
x_data = torch.tensor(data, dtype=torch.float32)
# torch.ones_like(x_data)
# x_tsr = torch.rand_like(x_data)
shape = (3, 2)
x_data = torch.rand(*shape)
x_data.shape, x_data.dtype, x_data.device

(torch.Size([3, 2]), torch.float32, device(type='cpu'))

In [70]:
x_data

tensor([[0.1854, 0.8905],
        [0.8094, 0.1615],
        [0.2485, 0.5539]])

In [89]:
torch.stack([x_data, x_data, x_data])

tensor([[[0.1854, 0.8905],
         [0.8094, 0.1615],
         [0.2485, 0.5539]],

        [[0.1854, 0.8905],
         [0.8094, 0.1615],
         [0.2485, 0.5539]],

        [[0.1854, 0.8905],
         [0.8094, 0.1615],
         [0.2485, 0.5539]]])

In [80]:
torch.cat([x_data, x_data, x_data], dim=0)

tensor([[0.1854, 0.8905],
        [0.8094, 0.1615],
        [0.2485, 0.5539],
        [0.1854, 0.8905],
        [0.8094, 0.1615],
        [0.2485, 0.5539],
        [0.1854, 0.8905],
        [0.8094, 0.1615],
        [0.2485, 0.5539]])

In [93]:
x_data = torch.rand(10, 2)
y_data = torch.rand(2, 5)
x_data, y_data

(tensor([[0.9329, 0.4413],
         [0.2326, 0.8322],
         [0.4375, 0.1135],
         [0.5835, 0.3859],
         [0.7960, 0.3477],
         [0.8802, 0.8373],
         [0.5571, 0.0098],
         [0.4450, 0.7611],
         [0.2903, 0.9045],
         [0.7543, 0.7739]]),
 tensor([[0.8411, 0.6756, 0.6380, 0.6892, 0.4511],
         [0.4211, 0.3567, 0.7206, 0.4561, 0.0196]]))

In [99]:
(x_data@y_data).sum().item()

30.1463565826416

In [105]:
x_data

tensor([[0.9329, 0.4413],
        [0.2326, 0.8322],
        [0.4375, 0.1135],
        [0.5835, 0.3859],
        [0.7960, 0.3477],
        [0.8802, 0.8373],
        [0.5571, 0.0098],
        [0.4450, 0.7611],
        [0.2903, 0.9045],
        [0.7543, 0.7739]])